# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

parameters:
  - name: password
    type: string
    default: A123456B
    displayName: Password
  - name: correo
    type: string
    default: mesa.cristian@gmail.com
    displayName: Correo

pool:
  name: default

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'clean test -Dpassword=${{parameters.password}} -Duser=${{parameters.correo}}'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
